project:
  type: website

website:
  title: "Kunal Khurana"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Kkhurana007
      - icon: twitter
        href: https://twitter.com/kunalkhurana007 
format:
  html:
    theme: cosmo
    css: styles.css



